/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Crop } from "./types";

export const PRESET_CROPS: Crop[] = [
  {
    id: "preset-1",
    name: "Papaya",
    scientificName: "Carica papaya",
    origin: "Originaria de las tierras bajas tropicales de Mesoamérica, entre el sur de México y Centroamérica.",
    description: "Planta herbácea arborescente de rápido crecimiento, con un tallo único y hueco coronado por grandes hojas palmeadas; produce frutos alargados de pulpa anaranjada y dulce.",
    uses: "Su fruto se consume fresco o en jugos y es rico en vitamina C y en papaína, una enzima que facilita la digestión. También se emplea como ablandador natural de carnes.",
    careLevel: "Moderado",
    sunlight: "Sol directo pleno (6-8 horas diarias)",
    waterRequirements: "Riego frecuente y abundante, con buen drenaje para evitar la pudrición de la raíz",
    harvestTime: "8-10 meses desde el trasplante",
    recommendedPriceSol: 0.02,
    recommendedPriceUsdc: 2.0,
    recommendedPriceUsdt: 2.0,
    priceSol: 0.018,
    priceUsdc: 1.8,
    priceUsdt: 1.8,
    stock: 8,
    scannedAt: "2026-05-30T09:15:00Z",
    isForSale: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Papaya_fruit_hanging_from_the_tree.jpg/500px-Papaya_fruit_hanging_from_the_tree.jpg",
    notes: "Ejemplar de huerto tropical en plena producción."
  },
  {
    id: "preset-2",
    name: "Prontoalivio",
    scientificName: "Lippia alba",
    origin: "Nativa de las regiones tropicales y subtropicales de América, desde México hasta Argentina.",
    description: "Arbusto perenne y aromático de silueta ramificada y hojas opuestas de borde aserrado, con pequeñas flores en tonos lila y blanco.",
    uses: "Sus hojas se usan en infusión como digestivo, sedante suave y para aliviar dolores estomacales y el nerviosismo. Muy apreciada en la medicina tradicional.",
    careLevel: "Fácil",
    sunlight: "Sol directo a media sombra (4-6 horas diarias)",
    waterRequirements: "Riego moderado; tolera periodos cortos de sequía",
    harvestTime: "90-120 días desde el esqueje",
    recommendedPriceSol: 0.015,
    recommendedPriceUsdc: 1.5,
    recommendedPriceUsdt: 1.5,
    priceSol: 0.012,
    priceUsdc: 1.2,
    priceUsdt: 1.2,
    stock: 10,
    scannedAt: "2026-05-30T10:40:00Z",
    isForSale: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Lippia_alba.jpg/500px-Lippia_alba.jpg",
    notes: "Planta medicinal aromática cultivada sin agroquímicos."
  },
  {
    id: "preset-3",
    name: "Aguacate (Palta)",
    scientificName: "Persea americana",
    origin: "Originario de México y Centroamérica, domesticado hace miles de años en Mesoamérica.",
    description: "Árbol de hoja perenne que produce frutos con forma de pera, de cáscara rugosa y pulpa cremosa de color verde a amarillo con una única semilla grande.",
    uses: "El fruto se consume fresco, en guacamole y ensaladas; es fuente de grasas saludables, potasio y vitamina E. La semilla y la hoja tienen usos tradicionales.",
    careLevel: "Moderado",
    sunlight: "Sol directo pleno (al menos 6 horas diarias)",
    waterRequirements: "Riego regular y profundo, evitando el encharcamiento",
    harvestTime: "Cosecha estacional; el fruto termina de madurar tras la recolección",
    recommendedPriceSol: 0.025,
    recommendedPriceUsdc: 2.5,
    recommendedPriceUsdt: 2.5,
    priceSol: 0.022,
    priceUsdc: 2.2,
    priceUsdt: 2.2,
    stock: 6,
    scannedAt: "2026-05-31T08:20:00Z",
    isForSale: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Avocado_Hass_-_single_and_halved.jpg/500px-Avocado_Hass_-_single_and_halved.jpg",
    notes: "Variedad de pulpa cremosa, ideal para consumo fresco."
  },
  {
    id: "preset-4",
    name: "Yuca",
    scientificName: "Manihot esculenta",
    origin: "Originaria de la cuenca del Amazonas, en la Sudamérica tropical.",
    description: "Arbusto perenne que puede alcanzar hasta 3 metros, de tallos leñosos y hojas palmeadas; almacena en sus raíces tuberosas grandes reservas de almidón.",
    uses: "Sus raíces son un alimento básico energético: se consumen hervidas, fritas o convertidas en harina y almidón (tapioca). Requiere cocción para eliminar compuestos amargos.",
    careLevel: "Moderado",
    sunlight: "Sol directo pleno (6-8 horas diarias)",
    waterRequirements: "Riego moderado; muy resistente a la sequía una vez establecida",
    harvestTime: "8-12 meses desde la siembra de la estaca",
    recommendedPriceSol: 0.012,
    recommendedPriceUsdc: 1.2,
    recommendedPriceUsdt: 1.2,
    priceSol: 0.01,
    priceUsdc: 1.0,
    priceUsdt: 1.0,
    stock: 9,
    scannedAt: "2026-05-31T11:05:00Z",
    isForSale: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Manihot_esculenta%2C_Cassava_root_-_Flickr_-_Dick_Culbert.jpg/500px-Manihot_esculenta%2C_Cassava_root_-_Flickr_-_Dick_Culbert.jpg",
    notes: "Raíces tuberosas listas para cosecha y venta."
  },
  {
    id: "preset-5",
    name: "Plátano Bizcochito",
    scientificName: "Musa × paradisiaca",
    origin: "Originario del sudeste asiático, hoy cultivado en todo el trópico americano.",
    description: "Fruto de una planta herbácea gigante con hojas muy grandes; sus dedos cortos y dulces se cosechan en racimos sobre un pseudotallo robusto.",
    uses: "Se consume fresco cuando madura o cocido (frito, asado, en patacones) cuando está verde. Es una importante fuente de carbohidratos y potasio.",
    careLevel: "Moderado",
    sunlight: "Sol directo pleno (6-8 horas diarias)",
    waterRequirements: "Riego abundante y constante; alta demanda de humedad",
    harvestTime: "9-12 meses hasta el primer racimo",
    recommendedPriceSol: 0.014,
    recommendedPriceUsdc: 1.4,
    recommendedPriceUsdt: 1.4,
    priceSol: 0.012,
    priceUsdc: 1.2,
    priceUsdt: 1.2,
    stock: 7,
    scannedAt: "2026-06-01T09:50:00Z",
    isForSale: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Bananas.jpg/500px-Bananas.jpg",
    notes: "Racimo de variedad pequeña y dulce, recién cosechado."
  },
  {
    id: "preset-6",
    name: "Bananito",
    scientificName: "Musa acuminata",
    origin: "Originaria del sudeste asiático y Oceanía, centro de domesticación del banano.",
    description: "Planta herbácea gigante de hojas oblongas verdes y brillantes, con un pseudotallo formado por las vainas foliares; produce racimos de bananos pequeños y muy dulces.",
    uses: "Sus frutos pequeños se comen frescos como postre; son ricos en azúcares, potasio y vitamina B6. Ideales para meriendas y batidos.",
    careLevel: "Moderado",
    sunlight: "Sol directo pleno (6-8 horas diarias)",
    waterRequirements: "Riego frecuente y abundante para mantener la humedad",
    harvestTime: "9-11 meses hasta el racimo",
    recommendedPriceSol: 0.013,
    recommendedPriceUsdc: 1.3,
    recommendedPriceUsdt: 1.3,
    priceSol: 0.011,
    priceUsdc: 1.1,
    priceUsdt: 1.1,
    stock: 9,
    scannedAt: "2026-06-01T12:30:00Z",
    isForSale: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Musa_acuminata1.jpg/500px-Musa_acuminata1.jpg",
    notes: "Variedad de banano enano, dulce y aromático."
  },
  {
    id: "preset-7",
    name: "Café",
    scientificName: "Coffea arabica",
    origin: "Originario de las tierras altas de Etiopía, en el cuerno de África.",
    description: "Arbusto perenne con hojas ovaladas de color verde oscuro y brillante; produce flores blancas fragantes y frutos rojos (cerezas) que contienen los granos de café.",
    uses: "De sus semillas tostadas y molidas se prepara el café. Se cultiva en altura para obtener tazas de mayor calidad, aroma y acidez equilibrada.",
    careLevel: "Moderado",
    sunlight: "Media sombra; prospera bajo dosel ligero (3-5 horas de sol filtrado)",
    waterRequirements: "Riego regular; clima húmedo y fresco de montaña",
    harvestTime: "3-4 años hasta la primera cosecha; las cerezas maduran de forma escalonada",
    recommendedPriceSol: 0.045,
    recommendedPriceUsdc: 4.5,
    recommendedPriceUsdt: 4.5,
    priceSol: 0.04,
    priceUsdc: 4.0,
    priceUsdt: 4.0,
    stock: 5,
    scannedAt: "2026-06-02T08:00:00Z",
    isForSale: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Coffea_Arabica_Healthy_Plant_Leaves_and_Berries.jpg/500px-Coffea_Arabica_Healthy_Plant_Leaves_and_Berries.jpg",
    notes: "Arbusto arábica de altura, con cerezas en maduración."
  },
  {
    id: "preset-8",
    name: "Toronjil",
    scientificName: "Lippia alba",
    origin: "Nativo de las zonas tropicales de América, ampliamente cultivado en huertos caseros.",
    description: "Arbusto aromático que alcanza entre 1 y 1.5 metros, de tallos finos y hojas fragantes de aroma cítrico, con flores pequeñas agrupadas.",
    uses: "Sus hojas se emplean en infusiones relajantes para calmar los nervios, conciliar el sueño y aliviar molestias digestivas.",
    careLevel: "Fácil",
    sunlight: "Sol directo a media sombra (4-6 horas diarias)",
    waterRequirements: "Riego moderado y constante, sin encharcar",
    harvestTime: "90-120 días desde el esqueje",
    recommendedPriceSol: 0.015,
    recommendedPriceUsdc: 1.5,
    recommendedPriceUsdt: 1.5,
    priceSol: 0.012,
    priceUsdc: 1.2,
    priceUsdt: 1.2,
    stock: 8,
    scannedAt: "2026-06-02T10:25:00Z",
    isForSale: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Lippia_alba.jpg/500px-Lippia_alba.jpg",
    notes: "Hierba aromática para infusiones, cultivada de forma orgánica."
  },
  {
    id: "preset-9",
    name: "Yuca",
    scientificName: "Manihot esculenta",
    origin: "Originaria de la cuenca del Amazonas, en la Sudamérica tropical.",
    description: "Planta arbustiva que alcanza entre 1.5 y 3 metros de altura, de tallos nudosos y hojas palmeadas; sus raíces engrosadas concentran almidón comestible.",
    uses: "Sus raíces se consumen hervidas, fritas o en harina; constituyen una fuente de energía fundamental en la dieta tropical. Debe cocinarse antes de su consumo.",
    careLevel: "Moderado",
    sunlight: "Sol directo pleno (6-8 horas diarias)",
    waterRequirements: "Riego moderado; muy resistente a la sequía una vez establecida",
    harvestTime: "8-12 meses desde la siembra de la estaca",
    recommendedPriceSol: 0.012,
    recommendedPriceUsdc: 1.2,
    recommendedPriceUsdt: 1.2,
    priceSol: 0.01,
    priceUsdc: 1.0,
    priceUsdt: 1.0,
    stock: 5,
    scannedAt: "2026-06-03T09:10:00Z",
    isForSale: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Manihot_esculenta%2C_Cassava_root_-_Flickr_-_Dick_Culbert.jpg/500px-Manihot_esculenta%2C_Cassava_root_-_Flickr_-_Dick_Culbert.jpg",
    notes: "Segundo lote de yuca, raíces frescas de buen calibre."
  },
  {
    id: "preset-10",
    name: "Tomate",
    scientificName: "Solanum lycopersicum",
    origin: "Originario de la región andina de Sudamérica y domesticado en Mesoamérica.",
    description: "Planta herbácea de tallos flexibles y hojas vellosas compuestas; produce frutos jugosos de color rojo intenso, redondeados y de sabor dulce-ácido.",
    uses: "Sus frutos se consumen frescos en ensaladas o cocidos en salsas y guisos; son ricos en licopeno, vitamina C y antioxidantes.",
    careLevel: "Moderado",
    sunlight: "Sol directo pleno (6-8 horas diarias)",
    waterRequirements: "Riego regular y uniforme; evitar mojar el follaje",
    harvestTime: "70-90 días desde el trasplante",
    recommendedPriceSol: 0.018,
    recommendedPriceUsdc: 1.8,
    recommendedPriceUsdt: 1.8,
    priceSol: 0.016,
    priceUsdc: 1.6,
    priceUsdt: 1.6,
    stock: 10,
    scannedAt: "2026-06-03T11:45:00Z",
    isForSale: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Bright_red_tomato_and_cross_section02.jpg/500px-Bright_red_tomato_and_cross_section02.jpg",
    notes: "Tomates de maduración en mata, cosechados a punto."
  },
  {
    id: "preset-11",
    name: "Caña de azúcar",
    scientificName: "Saccharum officinarum",
    origin: "Originaria de Nueva Guinea y el sudeste asiático tropical.",
    description: "Planta herbácea perenne de tallos altos, macizos y nudosos que almacenan un jugo rico en sacarosa; sus hojas son largas, acintadas y de borde áspero.",
    uses: "De sus tallos se extrae el jugo (guarapo) para producir azúcar, panela, melaza y etanol. También se mastica fresca por su dulzor.",
    careLevel: "Moderado",
    sunlight: "Sol directo pleno (al menos 6-8 horas diarias)",
    waterRequirements: "Riego abundante; alta demanda hídrica durante el crecimiento",
    harvestTime: "10-14 meses hasta el corte",
    recommendedPriceSol: 0.01,
    recommendedPriceUsdc: 1.0,
    recommendedPriceUsdt: 1.0,
    priceSol: 0.008,
    priceUsdc: 0.8,
    priceUsdt: 0.8,
    stock: 12,
    scannedAt: "2026-06-04T08:35:00Z",
    isForSale: true,
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Saccharum_officinarum%2C_Mozambique.jpg/500px-Saccharum_officinarum%2C_Mozambique.jpg",
    notes: "Cañaveral en sazón, tallos cargados de jugo dulce."
  }
];
